name: sputnik
description: BT Messenger
publish_to: 'none'
version: 1.1.0+14

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  cubit_form: ^1.0.18
  either_option: ^2.0.1-dev.1
  equatable: ^2.0.3
  flutter_bloc: ^7.0.1
  get_it: ^7.1.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  image_picker: ^0.8.1+1
  intl: ^0.17.0
  ionicons: ^0.1.2
  json_annotation: ^4.0.1
  jwt_decoder: ^2.0.1
  permission_handler: ^8.1.1
  pretty_dio_logger: ^1.2.0-beta-1
  stream_chat_flutter_core: ^3.0.0
  timeago: ^3.1.0
  url_launcher: ^6.0.7
  cupertino_icons: ^1.0.3
  flutter_contacts: ^1.1.1+2
  telephony: ^0.1.4
  flutter_email_sender: ^5.0.2
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  flutter_libphonenumber: ^1.1.0
  get: ^4.1.4
  solid_bottom_sheet: ^0.1.10
  rflutter_alert: ^2.0.2
  file_picker: ^4.0.0
  cached_network_image: ^3.1.0
  sentry_flutter: ^6.0.0
  open_file: ^3.2.1
  flutter_cache_manager: ^3.1.2
  image_cropper: ^1.4.1
  badges: ^2.0.1
  # virgil_e3kit: 0.0.1
#    git:
#      url: git://github.com/ShahzadUmarBaig/virgil-e3kit-flutter
#      ref: 2314c27632d5d1032ca2823d99440ec598919870
  sliding_up_panel: ^2.0.0+1
  flutter_local_notifications: ^8.1.1+2
  flutter_sms: ^2.3.1
  firebase_messaging: ^10.0.6
  firebase_core: ^1.6.0
  flutter_secure_storage: ^4.2.1
  pull_to_refresh: ^2.0.0
  back_button_interceptor: ^5.0.2
  animations: ^2.0.1
  image_gallery_saver: ^1.7.1
  modal_bottom_sheet: ^2.0.0
  package_info_plus: ^1.3.0
  scrollable_positioned_list: ^0.2.2


dev_dependencies:
  flutter_launcher_icons: "^0.9.1"
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/app_icon/
    - assets/images/
    - assets/chat_backgrounds/
  fonts:
    - family: BrandIcons
      fonts:
        - asset: assets/fonts/BrandIcons.ttf

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/app_icon/app_icon.png"
  image_path_ios: "assets/app_icon/app_icon_ios.png"

#flutter_native_splash:
#  image: assets/images/splash.png
#  color: "141B23"
#  color_dark: "141B23"
#  fill: true
